---
id: mariadb-community-event-2016-07-21
base_name: mroonga
tags:
- rabbit
- mroonga
- mariadb
- groonga
presentation_date: 2016-07-21
version: 2016.7.21.1
licenses:
- CC BY-SA 4.0
- CC BY 3.0
slideshare_id: mariadb-community-event-2016-07-21
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
